version: "3.9"

networks:
    laravel:


services:
    nginx:
        networks:
            - laravel

    mysql:
        networks:
            - laravel

    php:
        networks:
            - laravel
