version: "3.9"

networks:
    laravel:


services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        port:
            - 8088:80
        volumes:
            - .:/var/www/l9-with-sass
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        networks:
            - laravel

    php:
        networks:
            - laravel
