version: "3.9"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8088:80
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 4306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_DATABASE: homestead
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ../:/var/www/html
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        # writes npm before our command 
        entrypoint: ['npm']
        networks:
            - laravel


