version: "3.9"

networks:
    laravel:


services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8088:80
        volumes:
            - ../:/var/www/l9-with-sass
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
            # unblock this comment if you wat your mysql to be persisted (I recommnent to use seeders to set the data for dev)
            # volumes:
            # - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER_NAME: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - laravel

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ../:/var/www/l9-with-sass
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ../:/var/www/l9-with-sass
        depends_on:
            - php
        working_dir: /var/www/l9-with-sass
         # writes npm before our command. So, instead `docker-compose run --rm composer composer install` we can go for `docker-compose run --rm composer install`
        entrypoint: composer
        command: install
        # this command will make the composer run for ever.
        # command: tail -f /dev/null
        networks:
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ../:/var/www/l9-with-sass
        working_dir: /var/www/l9-with-sass
        # writes npm before our command. So, instead `docker-compose run --rm npm npm install` we can go for `docker-compose run --rm npm install`
        entrypoint: npm
        # keep this command to install npm dependencies if entry point is
        command: install
        networks:
            - laravel

    artisan:
        build:
            context: ./dockerfiles
            dockerfile: artisan.dockerfile
        container_name: artisan
        volumes:
            - ../:/var/www/l9-with-sass
        depends_on:
            - mysql
            - composer
        working_dir: /var/www/l9-with-sass
        entrypoint: php artisan
        networks:
            - laravel



