version: "3.9"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8088:80
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER_NAME: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ../:/var/www/html
            # - ../docker/php.init:/usr/local/etc/php/php.ini
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        # writes npm before our command. So, instead `docker-compose -rm npm npm install` we can go for `docker-compose -rm npm install`
        # entrypoint: ['npm']
        # this command will not make the npm container stop and we can run the commands in the command line. 
        command: tail -f /dev/null
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ../:/var/www/html
        # depends_on:
        #     - mysql
        working_dir: /var/www/html
        # writes /var/www/html/artisan before our command
        entrypoint: ['/var/www/html/artisan']
        command: tail -f /dev/null
        networks:
            - laravel


